apiVersion: appsody.dev/v1beta1
kind: AppsodyApplication
metadata:
  annotations:
    commit.image.appsody.dev/date: Thu Jun 4 15:40:15 2020 -0400
    commit.image.appsody.dev/message: added a Cloudant query for /companies
    commit.stack.appsody.dev/author: Harish Yayi <yharish991@gmail.com>
    commit.stack.appsody.dev/committer: GitHub <noreply@github.com>
    commit.stack.appsody.dev/contextDir: /incubator/java-spring-boot2
    commit.stack.appsody.dev/date: Thu Jun 4 12:03:56 2020 +0100
    commit.stack.appsody.dev/message: 'java-springboot2: define APPSODY_DEBUG_PORT
      (#819)'
    image.opencontainers.org/created: "2020-06-05T14:51:56-04:00"
    image.opencontainers.org/documentation: https://github.com/richard-trotter/stock-advisor
    image.opencontainers.org/revision: e062cb5e32b4ebef48ade28cb1308db27404a642-modified
    image.opencontainers.org/source: https://github.com/richard-trotter/stock-advisor/tree/master
    image.opencontainers.org/url: https://github.com/richard-trotter/stock-advisor
    stack.appsody.dev/authors: Erin Schnabel <ebullient>, Ozzy Osborne <bardweller>,
      Richard Trotter <richard-trotter>, Harish Yayi <yharish991>
    stack.appsody.dev/configured: docker.io/appsody/java-spring-boot2:0.3
    stack.appsody.dev/created: "2020-06-04T11:06:14Z"
    stack.appsody.dev/description: Spring Boot using OpenJ9 and Maven
    stack.appsody.dev/digest: sha256:b1dc6398a112888f2b4a5e46a517f5f39b13d0712132e2ec53d9382c15be8aaa
    stack.appsody.dev/documentation: https://github.com/appsody/stacks/tree/master/incubator/java-spring-boot2/README.md
    stack.appsody.dev/licenses: Apache-2.0
    stack.appsody.dev/revision: 7417563d37f987bc803711298b29817519cc648d
    stack.appsody.dev/source: https://github.com/appsody/stacks/tree/master/incubator/java-spring-boot2/image
    stack.appsody.dev/tag: docker.io/appsody/java-spring-boot2:0.3.30
    stack.appsody.dev/title: Spring Boot®
    stack.appsody.dev/url: https://github.com/appsody/stacks/tree/master/incubator/java-spring-boot2
  creationTimestamp: null
  labels:
    image.opencontainers.org/title: stock-advisor
    stack.appsody.dev/id: java-spring-boot2
    stack.appsody.dev/version: 0.3.30
  name: stock-advisor
spec:
  applicationImage: dev.local/stock-advisor
  createKnativeService: false
  expose: true
  livenessProbe:
    failureThreshold: 12
    httpGet:
      path: /actuator/liveness
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 2
  monitoring:
    endpoints:
    - path: /actuator/prometheus
    labels:
      k8s-app: stock-advisor
  readinessProbe:
    failureThreshold: 12
    httpGet:
      path: /actuator/health
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 2
    timeoutSeconds: 1
  service:
    annotations:
      prometheus.io/path: /actuator/prometheus
      prometheus.io/scrape: "true"
    port: 8080
    type: NodePort
  stack: java-spring-boot2
  version: 1.0.0
  volumeMounts:
  - mountPath: /etc/secrets/alphavantage
    name: alphavantage-secrets
    readOnly: true
  - mountPath: /etc/secrets/cloudant
    name: cloudant-secrets
    readOnly: true
  - mountPath: /etc/secrets/watson
    name: watson-secrets
    readOnly: true
  volumes:
  - name: alphavantage-secrets
    secret:
      secretName: alphavantage-access
  - name: cloudant-secrets
    secret:
      secretName: cloudant-access
  - name: watson-secrets
    secret:
      secretName: discovery-access
