apiVersion: v1
kind: Secret
metadata:
  name: alphavantage-access
type: Opaque
data:
  alphavantage.baseurl: ${alphavantage_baseurl}
  alphavantage.apikey: ${alphavantage_apikey}
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudant-access
type: Opaque
data:
  cloudant.url: ${cloudant_url}
  cloudant.apikey: ${cloudant_apikey}
  cloudant.db_name: ${cloudant_db_name}
---
apiVersion: v1
kind: Secret
metadata:
  name: discovery-access
type: Opaque
data:
  watson.discovery.url: ${watson_discovery_url}
  watson.discovery.iam_apikey: ${watson_discovery_iam_apikey}
